name: .NET with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner for .NET
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"Encrypt0n_MDE-API" \
            /o:"encrypt0n" \
            /d:sonar.token="43481cfa073dc3c47dfbba6d8cb7de73495730ad" \
            /d:sonar.projectBaseDir="$(pwd)" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"


      - name: Build
        run: dotnet build --no-incremental

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage"
          reportPath=$(find . -type f -name 'coverage.opencover.xml' | head -n 1)
          echo "Coverage report located at: $reportPath"

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="43481cfa073dc3c47dfbba6d8cb7de73495730ad"
