name: .NET with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"Encrypt0n_MDE-API" \
            /o:"encrypt0n" \
            /d:sonar.login="43481cfa073dc3c47dfbba6d8cb7de73495730ad" \
            /d:sonar.cs.opencover.reportsPaths="TestResults/coverage.opencover.xml" \
            /d:sonar.verbose=true \
            /d:sonar.projectBaseDir="$(pwd)/.."  # adjust if needed

      - name: Build solution
        run: dotnet build --no-incremental

      - name: Run tests with coverage
        run: |
          coverlet ./MDE_API.Tests/bin/Debug/net8.0/MDE_API.Tests.dll \
            --target "dotnet" \
            --targetargs "test --no-build --no-restore" \
            --format opencover \
            --output ./TestResults/coverage.opencover.xml

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="43481cfa073dc3c47dfbba6d8cb7de73495730ad"
