name: .NET with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with coverage
      run: |
        coverlet ./MDE_API.Tests/bin/Debug/net8.0/MDE_API.Tests.dll \
        --target "dotnet" \
        --targetargs "test --no-build --no-restore" \
        --format opencover \
        --output ./TestResults/coverage.opencover.xml
    
    - name: List coverage output
      run: ls -la coverage/

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v5.0.0
      with:
        args: >
          -Dsonar.cs.opencover.reportsPaths=coverage/coverage.opencover.xml
      env:
        SONAR_TOKEN: 43481cfa073dc3c47dfbba6d8cb7de73495730ad
